version: '3'
services:
  frp-http-server:
    container_name: frp-http-server
    # tty: true
    # stdin_open: true
    environment:
      - FRP_SUBDOMAIN_HOST=nwct.dev
      - SERVER_IP=xxx.xxx.xxx.xxx
    ports:
      - "8001:80"
      - "7000:7000"
    build: .
