#!/command/with-contenv bash
# shellcheck shell=bash
echo "10-FRP_SUBDOMAIN_HOST: ${FRP_SUBDOMAIN_HOST}"
exec /usr/bin/frps \
  --bind_port="7000" \
  --subdomain_host="${FRP_SUBDOMAIN_HOST}" \
  --vhost_http_port="7080" \
  --dashboard_port="7500" \
  --dashboard_user="" \
  --dashboard_pwd=""
