#!/command/with-contenv bash
# shellcheck shell=bash
echo "10-FRP_SUBDOMAIN_HOST: ${FRP_SUBDOMAIN_HOST}"
# 如果 frps 配置了 subdomain_host ，则frpc中想自定义custom_domains 中不能是属于 subdomain_host 的子域名或者泛域名。
exec /usr/bin/frps \
  --bind_port="7000" \
  --subdomain_host="${FRP_SUBDOMAIN_HOST}" \
  --vhost_http_port="7080" \
  --dashboard_port="7500" \
  --dashboard_user="" \
  --dashboard_pwd=""
